var a,b,c;
var a=5;
var b=6;
var c=7;
var p=0;
var S=0;
var p=(a+b+c)/2;
var S=Math.sqrt(p*(p-a)*(p-b)*(p-c));
alert("The area of the triangle is : "+ S);
console.log("The area of the triangle is : "+ S);